apiVersion: apps/v1
kind: Deployment
metadata:
  name: pintu-app 
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: pintu-app
        image: makinglaugh/pintu:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pintu-app
  namespace: workflow
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001